name: Create release

on:
  workflow_dispatch:

jobs:
  run_tests:
    name: Run pre-release tests
    uses: ./.github/workflows/tests.yaml

  build_sdist:
    runs-on: ubuntu-latest
    needs: [run_tests]

    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10"

      - name: Build sdist
        run: |
          pdm build --no-wheel

      - name: Save version
        run: |
          echo "$(pdm show asgi_context --version)" > version.txt

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: version.txt

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v3
        with:
          path: "dist"

  build_wheels:
    runs-on: ${{ matrix.os }}
    needs: [run_tests]

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: |
          pdm build --no-sdist

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v3
        with:
          path: "dist"

  create_gh_release:
    runs-on: ubuntu-latest
    needs: [build_sdist, build_wheels]
    steps:
      - name: Download version
        uses: actions/download-artifact@v3
        with:
          name: version

      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          path: "dist"

      - name: Set version env var
        run: |
          echo "VERSION=$(cat version.txt | tr -d '\n')" >> "$GITHUB_ENV"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            dist/*
